# Exercice
Implémentez une  **trier (classeur, valeur)** qui place une valeur dans un dictionnaire en fonction de son signe

In [17]:
import numpy as np

# Fonction qui ajoute la valeur à la bonne liste, puis tri la liste
def addAndSort(classeur, valeur):
    if valeur < 0:
        classeur['négatifs'].append(valeur)
        classeur['négatifs'] = sorted(classeur['négatifs'])
    else:
        classeur['positifs'].append(valeur)
        classeur['positifs'] = sorted(classeur['positifs'])
    return classeur


# Propose à l'utilisateur de saisir les valeurs
def userInput():
    print("Saisissez un nombre positif ou négatif ou exit pour quitter:")
    exit = False

    while (not exit):
        saisie = input()
        exit = str(saisie) == "exit"

        if exit :
            break
        else:
            try:
                nb = float(saisie)
                classeur = addAndSort(classeur, nb)
                break
            except ValueError:
                print("Oops!  Saisissez un nombre positif ou négatif ou exit pour quitter\nTry again...")

                
# Génère une liste de valeurs aléatoire dans l'intervale
def generateListValues(nbVal):
    values = []
    for i in range(nbVal):
        nb = np.random.randint(-100, 100)
        values.append(nb)
    print("Valeurs de départ", values)
    return values                
                

def autoInput(classeur):
    values = generateListValues(40)
    for val in values:
        classeur = addAndSort(classeur, val)
    return classeur
    
    
# Début du programme
classeur = {'négatifs':[],
            'positifs':[]}

classeur = autoInput(classeur)

print("-------------------------------------------------------------------")
print('négatifs', classeur['négatifs'])
print('positifs', classeur['positifs'])



Valeurs de départ [-83, -22, 91, 90, -81, -91, -21, 4, -43, -75, -56, 16, -48, -23, 30, -23, -44, 27, 44, 71, 28, 42, -34, 22, 30, -79, 16, 87, -62, -57, 12, 23, -29, -86, 77, 62, -46, -94, -72, 38]
-------------------------------------------------------------------
négatifs [-94, -91, -86, -83, -81, -79, -75, -72, -62, -57, -56, -48, -46, -44, -43, -34, -29, -23, -23, -22, -21]
positifs [4, 12, 16, 16, 22, 23, 27, 28, 30, 30, 38, 42, 44, 62, 71, 77, 87, 90, 91]


# Exercice 2
On considère la fonction $f$ définie par : **$f (x) = sin(x) − x$**.
1. Définir la fonction f dans Python en utilisant la bibliothèque numpy.
2. Définir une liste X1 contenant 20 valeurs régulièrement espacées entre 10 et 30. Définir une liste $Y_1$ contenant 20 valeurs définies par $Y_1[i]= f (X_1[i])$.On utilisera la syntaxe range.
3. Définir un tableau numpy $X_2$ contenant 20 valeurs régulièrement espacésentre 10 et 30. Définir un tableau $Y_2$ contenant 20 valeurs définies par $Y[i]=f (X[i])$. On utilisera la syntaxe range.
4. Définir un tableau numpy X3 contenant 20 valeurs régulièrement espacésentre 10 et 30 en utilisant la syntaxe **np.linspace**. 
    Définir un tableau $Y_3$ contenant 11 valeurs définies par $Y[i]= f (X[i])$ sans utiliser la syntaxe range

In [69]:
import numpy as np
from random import randint

#𝑓(𝑥)=𝑠𝑖𝑛(𝑥)−𝑥
def f(x):
    res = np.sin(x) - x
    return res
# Fonction courte
#f=lambda x:np.sin(x) - x

#----------------------------------------
# X1 contenant 20 valeurs régulièrement espacées entre 10 et 30.
# Définir une liste 𝑌1 contenant 20 valeurs définies par 𝑌1[𝑖]=𝑓(𝑋1[𝑖]).On utilisera la syntaxe range
X1 = []
Y1 = []
for i in range (10, 30, 1):
    X1.append(i)
    # 𝑌1[𝑖]=𝑓(𝑋1[𝑖])
    Y1.append(f(i))
print("X1 :", X1)
print("----------------------------------------")   
print("Y1 :", Y1)
print("---------------------------------------------------------------------------------------------------------")
# 𝑋2 contenant 20 valeurs régulièrement espacésentre 10 et 30.
# Définir un tableau 𝑌2 contenant 20 valeurs définies par 𝑌[𝑖]=𝑓(𝑋[𝑖]). On utilisera la syntaxe range
X2= np.arange (10, 30, 1)
Y2= []
for i in X2:
    # 𝑌[𝑖]=𝑓(𝑋[𝑖])
    Y2.append(f(i))
print("X2 :", X2)
print("----------------------------------------")
print("Y2 :", Y2)
print("---------------------------------------------------------------------------------------------------------")
# X3 contenant 20 valeurs régulièrement espacésentre 10 et 30 en utilisant la syntaxe np.linspace.
# Définir un tableau 𝑌3 contenant 11 valeurs définies par 𝑌[𝑖]=𝑓(𝑋[𝑖]) sans utiliser la syntaxe range
X3 = np.linspace(10, 30, 20, dtype=int)
Y3 = f(X3[0:11])
print("X3 :", X3)
print("----------------------------------------")
print("Y3 :", Y3)

X1 : [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
----------------------------------------
Y1 : [-10.54402111088937, -11.999990206550704, -12.536572918000434, -12.57983296317336, -13.00939264430513, -14.349712159842884, -16.287903316665066, -17.961397491879556, -18.750987246771675, -18.850122790337046, -19.087054749272372, -20.163344361463945, -22.008851309290403, -23.84622040417517, -24.905578362006622, -25.132351750097772, -25.237441549520398, -26.043624071595495, -27.729094211692132, -29.663633884212967]
---------------------------------------------------------------------------------------------------------
X2 : [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
----------------------------------------
Y2 : [-10.54402111088937, -11.999990206550704, -12.536572918000434, -12.57983296317336, -13.00939264430513, -14.349712159842884, -16.287903316665066, -17.961397491879556, -18.750987246771675, -18.850122790337046, -19.087054749272372, -20

# Exercice 3

In [71]:
import numpy as np


def initialisation(m, n):
    # m : nombre de lignes
    # n : nombre de colonnes
    # retourne une matrice aléatoire (m, n+1)
    # avec une colonne biais (remplie de "1") tout a droite

    #Initialisation de la matrice avec des valeurs aléatoires
    matrice = np.zeros((m, n+1))
    print('The value is :', matrice)
    # if we check the matrix dimensions
    # using shape:
    print('The shape of matrix is :', matrice.shape)
    # by default the matrix type is float64
    print('The type of matrix is :', matrice.dtype)
    # Ajout de la colonne de biais

    for ligne in range(m):
        # Initialisation du tableau représentant la ligne
        lineTab = matrice[ligne]
        for col in range(n + 1):
            # On traite le cas du biais
            nb = 1
            if (col < n):
                nb = np.random.randint(-100, 100)
            lineTab[col] = nb
        # Ajout de la ligne à la matrice générale
        #matrice[ligne] = lineTab
    print('The value is :', matrice)
    return matrice


def printMatrice(matrice):
    # nombre de lignes et col, shape renvoie un tuple
    nbDim = matrice.shape
    nbLigne = nbDim[0]
    nbCol = nbDim[1]
    print("nbDim:",nbDim,"nbLigne:",nbLigne,"x nbCol:",nbCol)
    print(matrice)



matrice = initialisation(5, 4)
printMatrice(matrice)

The value is : [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
The shape of matrix is : (5, 5)
The type of matrix is : float64
The value is : [[ 84.  55. -51.  84.   1.]
 [  0. -19. -17.  86.   1.]
 [-13.  11. -20.  30.   1.]
 [-53.  88. -84. -40.   1.]
 [ 15.  39. -67. -48.   1.]]
nbDim: (5, 5) nbLigne: 5 x nbCol: 5
[[ 84.  55. -51.  84.   1.]
 [  0. -19. -17.  86.   1.]
 [-13.  11. -20.  30.   1.]
 [-53.  88. -84. -40.   1.]
 [ 15.  39. -67. -48.   1.]]


# Exercice 4
1. Créer deux matrices $R =\pmatrix{1&2&3\\
                                    4&5&6}$ et $S =\pmatrix{1&2&3\\
                                                 4&5&6\\
                                                 7&8&9.}$.
Les afficher avec Python.

2. Créer une fonction test, d'argument M, renvoyant la valeur n si M est une matrice carrée d’ordre n (entier naturel non nul), et zéro dans tous les autres cas.Vérifier la fonction test sur R et sur S.

3. Déterminer les valeurs propres et les vecteurs propres de la matrice $A =\pmatrix{5& −3\\6& −4}$ en utilisant la fonction eig. Vérifier les propriétés des valeurspropres et des vecteurs propres de la matrice A.

In [72]:
import numpy as np
#Créer deux matrices 𝑅=(142536) et 𝑆=Les afficher avec Python.
def exo4():
    print("---------------------------- EXERCICE 4 -----------------------------------")
    # affectation des valeurs
    r = np.array([[1,2,3],[4,5,6]])
    s = np.array([[1,2,3],[4,5,6],[7,8,9]])
    print("R=", r)
    print("S=", s)
    #n = entier naturel non nul, renvoie  zéro dans tous les autres cas
    print("R, donc attendu 0, obtenu :", test(r))
    print("S, donc attendu n, obtenu :", test(s))


#Renvoyant la valeur n si M est une matrice carrée d’ordre n (entier naturel non nul),
# et zéro dans tous les autres cas.
def test(matrice):
    # Vérifie que la matrice a autant de ligne que de colonne
    nbDim = matrice.shape
    res = 0
    
    if(nbDim[0]==nbDim[1]):
        res = matrice.size
        for ligne in range(nbDim[0]):
            # Initialisation du tableau représentant la ligne
            lineTab = matrice[ligne]
            for col in range(nbDim[1]):
                nb = lineTab[col]
                # Vérifier que les valeurs dans la matrice sont des entiers naturel non nul
                if(not np.issubdtype(nb, np.integer) or nb < 0):
                     res = 0
                     break
    return res


exo4()

---------------------------- EXERCICE 4 -----------------------------------
R= [[1 2 3]
 [4 5 6]]
S= [[1 2 3]
 [4 5 6]
 [7 8 9]]
R, donc attendu 0, obtenu : 0
S, donc attendu n, obtenu : 9


# Exercice 5 : Slicing, ou découpage en tranches,et range, np.arange, np.linspace
On considère le programme suivant :

In [1]:
import numpy as np
L1=[ ]
for i in range(2,7,2):
    L1.append(i)
print('L1 = ',L1)
print(L1[:-1])
T1=np.arange(2,7,2)
print('T1 = ',T1)
print(T1[1:3])
x1=np.linspace(0,np.pi,5)
print('x1 = ',x1)
print('x1[1:3] = ',x1[1:3])

L1 =  [2, 4, 6]
[2, 4]
T1 =  [2 4 6]
[4 6]
x1 =  [0.         0.78539816 1.57079633 2.35619449 3.14159265]
x1[1:3] =  [0.78539816 1.57079633]


**Qu’affiche Python lors de l’exécution du programme ?**

**Analyse du problème**
La technique du slicing, ou découpage par tranches, permet d’extraire des élé-ments d’une liste ou d’un tableau. 
On l’utilise également pour les fonctions **range**, **np.arange** et **np.linspace**.